# Generated by Django 3.2 on 2023-11-28 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_order_orderitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='comment',
            new_name='reviews',
        ),
    ]
